import type { FilterDef } from "../contracts"
import {
  boxBlur,
  averageBlur,
  smartBlur,
  despeckle,
  ntscColors,
  glowingEdges,
  wind,
  extrude,
  renderFlame,
  pictureFrame,
  renderTree,
  displace,
  shapeBlur,
  diffuseGlow,
  oceanRipple,
  legacyGalleryDefs,
  PROMOTED_GALLERY_FILTERS,
  fragment,
  facet,
  pointillize,
  shear,
  tilesFilter,
  diffuse,
  deInterlaceAdvanced,
} from "../registry-helpers"

export const legacyFilters: Record<string, FilterDef> = {
  ...legacyGalleryDefs([
    { id: "colored-pencil", name: "Colored Pencil", category: "Artistic" },
    { id: "cutout", name: "Cutout", category: "Artistic" },
    { id: "dry-brush", name: "Dry Brush", category: "Artistic" },
    { id: "film-grain", name: "Film Grain", category: "Artistic" },
    { id: "fresco", name: "Fresco", category: "Artistic" },
    { id: "neon-glow", name: "Neon Glow", category: "Artistic" },
    { id: "paint-daubs", name: "Paint Daubs", category: "Artistic" },
    { id: "palette-knife", name: "Palette Knife", category: "Artistic" },
    { id: "plastic-wrap", name: "Plastic Wrap", category: "Artistic" },
    { id: "poster-edges", name: "Poster Edges", category: "Artistic" },
    { id: "rough-pastels", name: "Rough Pastels", category: "Artistic" },
    { id: "smudge-stick", name: "Smudge Stick", category: "Artistic" },
    { id: "sponge-filter", name: "Sponge", category: "Artistic" },
    { id: "underpainting", name: "Underpainting", category: "Artistic" },
    { id: "watercolor", name: "Watercolor", category: "Artistic" },
    { id: "accented-edges", name: "Accented Edges", category: "Brush Strokes" },
    { id: "angled-strokes", name: "Angled Strokes", category: "Brush Strokes" },
    { id: "crosshatch", name: "Crosshatch", category: "Brush Strokes" },
    { id: "dark-strokes", name: "Dark Strokes", category: "Brush Strokes" },
    { id: "ink-outlines", name: "Ink Outlines", category: "Brush Strokes" },
    { id: "spatter", name: "Spatter", category: "Brush Strokes" },
    { id: "sprayed-strokes", name: "Sprayed Strokes", category: "Brush Strokes" },
    { id: "sumi-e", name: "Sumi-e", category: "Brush Strokes" },
    { id: "bas-relief", name: "Bas Relief", category: "Sketch" },
    { id: "chalk-charcoal", name: "Chalk & Charcoal", category: "Sketch" },
    { id: "charcoal", name: "Charcoal", category: "Sketch" },
    { id: "chrome", name: "Chrome", category: "Sketch" },
    { id: "conte-crayon", name: "Conte Crayon", category: "Sketch" },
    { id: "graphic-pen", name: "Graphic Pen", category: "Sketch" },
    { id: "halftone-pattern", name: "Halftone Pattern", category: "Sketch" },
    { id: "note-paper", name: "Note Paper", category: "Sketch" },
    { id: "photocopy", name: "Photocopy", category: "Sketch" },
    { id: "plaster", name: "Plaster", category: "Sketch" },
    { id: "reticulation", name: "Reticulation", category: "Sketch" },
    { id: "stamp-filter", name: "Stamp", category: "Sketch" },
    { id: "torn-edges", name: "Torn Edges", category: "Sketch" },
    { id: "water-paper", name: "Water Paper", category: "Sketch" },
    { id: "craquelure", name: "Craquelure", category: "Texture" },
    { id: "grain", name: "Grain", category: "Texture" },
    { id: "mosaic-tiles", name: "Mosaic Tiles", category: "Texture" },
    { id: "patchwork", name: "Patchwork", category: "Texture" },
    { id: "stained-glass", name: "Stained Glass", category: "Texture" },
    { id: "texturizer", name: "Texturizer", category: "Texture" },
  ]),
  ...PROMOTED_GALLERY_FILTERS,
  "average-blur": { id: "average-blur", name: "Average", category: "Blur", params: [], apply: (src) => averageBlur(src) },
  "blur-more": { id: "blur-more", name: "Blur More", category: "Blur", params: [], apply: (src) => boxBlur(src, 3) },
  "smart-blur": {
    id: "smart-blur",
    name: "Smart Blur",
    category: "Blur",
    params: [
      { type: "slider", key: "radius", label: "Radius", min: 0.1, max: 32, step: 0.1, default: 4, suffix: "px" },
      { type: "slider", key: "threshold", label: "Threshold", min: 0, max: 255, step: 1, default: 38 },
    ],
    apply: (src, p) => smartBlur(src, Number(p.radius), Number(p.threshold)),
  },
  "shape-blur": {
    id: "shape-blur",
    name: "Shape Blur",
    category: "Blur",
    params: [
      { type: "slider", key: "radius", label: "Radius", min: 1, max: 40, step: 1, default: 8, suffix: "px" },
      { type: "select", key: "shape", label: "Shape", options: [
        { value: "circle", label: "Circle" },
        { value: "diamond", label: "Diamond" },
        { value: "line", label: "Line" },
      ], default: "circle" },
    ],
    apply: (src, p) => shapeBlur(src, Number(p.radius), String(p.shape)),
  },
  despeckle: { id: "despeckle", name: "Despeckle", category: "Noise", params: [], apply: (src) => despeckle(src) },
  "ntsc-colors": { id: "ntsc-colors", name: "NTSC Colors", category: "Video", params: [], apply: (src) => ntscColors(src) },
  "de-interlace": {
    id: "de-interlace",
    name: "De-Interlace",
    category: "Video",
    params: [
      { type: "select", key: "field", label: "Eliminate", options: [
        { value: "even", label: "Even Fields" },
        { value: "odd", label: "Odd Fields" },
      ], default: "even" },
      { type: "select", key: "method", label: "Create New Fields by", options: [
        { value: "duplication", label: "Duplication" },
        { value: "interpolation", label: "Interpolation" },
      ], default: "interpolation" },
    ],
    apply: (src, p) => deInterlaceAdvanced(src, String(p.field ?? "even"), String(p.method ?? "interpolation")),
  },
  "glowing-edges": {
    id: "glowing-edges",
    name: "Glowing Edges",
    category: "Stylize",
    params: [
      { type: "slider", key: "width", label: "Edge Width", min: 1, max: 14, step: 1, default: 4 },
      { type: "slider", key: "brightness", label: "Brightness", min: 0, max: 100, step: 1, default: 55 },
      { type: "slider", key: "smooth", label: "Smoothness", min: 0, max: 10, step: 1, default: 2 },
    ],
    apply: (src, p) => glowingEdges(src, Number(p.width), Number(p.brightness), Number(p.smooth)),
  },
  wind: {
    id: "wind",
    name: "Wind",
    category: "Stylize",
    params: [
      { type: "slider", key: "strength", label: "Strength", min: 1, max: 30, step: 1, default: 12 },
      { type: "select", key: "direction", label: "Direction", options: [
        { value: "right", label: "From Left" },
        { value: "left", label: "From Right" },
      ], default: "right" },
    ],
    apply: (src, p) => wind(src, Number(p.strength), String(p.direction)),
  },
  extrude: {
    id: "extrude",
    name: "Extrude",
    category: "Stylize",
    params: [
      { type: "slider", key: "depth", label: "Depth", min: 1, max: 80, step: 1, default: 18, suffix: "px" },
      { type: "select", key: "mode", label: "Type", options: [
        { value: "blocks", label: "Blocks" },
        { value: "pyramid", label: "Pyramids" },
      ], default: "blocks" },
    ],
    apply: (src, p) => extrude(src, Number(p.depth), String(p.mode)),
  },
  flame: {
    id: "flame",
    name: "Flame",
    category: "Render",
    params: [
      { type: "slider", key: "height", label: "Height", min: 10, max: 100, step: 1, default: 45, suffix: "%" },
      { type: "slider", key: "turbulence", label: "Turbulence", min: 0, max: 100, step: 1, default: 55, suffix: "%" },
    ],
    apply: (src, p) => renderFlame(src, Number(p.height), Number(p.turbulence)),
  },
  "picture-frame": {
    id: "picture-frame",
    name: "Picture Frame",
    category: "Render",
    params: [
      { type: "slider", key: "size", label: "Frame Size", min: 1, max: 120, step: 1, default: 28, suffix: "px" },
      { type: "select", key: "color", label: "Color", options: [
        { value: "#111827", label: "Graphite" },
        { value: "#8b5cf6", label: "Violet" },
        { value: "#f8fafc", label: "White" },
        { value: "#92400e", label: "Walnut" },
      ], default: "#111827" },
    ],
    apply: (src, p) => pictureFrame(src, Number(p.size), String(p.color)),
  },
  tree: {
    id: "tree",
    name: "Tree",
    category: "Render",
    params: [
      { type: "slider", key: "branches", label: "Branches", min: 2, max: 5, step: 1, default: 3 },
      { type: "checkbox", key: "leaves", label: "Leaves", default: true },
    ],
    apply: (src, p) => renderTree(src, Number(p.branches), Boolean(p.leaves)),
  },
  displace: {
    id: "displace",
    name: "Displace",
    category: "Distort",
    params: [
      { type: "slider", key: "scaleX", label: "Horizontal Scale", min: -200, max: 200, step: 1, default: 24 },
      { type: "slider", key: "scaleY", label: "Vertical Scale", min: -200, max: 200, step: 1, default: 24 },
      { type: "select", key: "map", label: "Displacement Map", options: [
        { value: "image", label: "Image (Displacement Map…)" },
        { value: "noise", label: "Procedural Noise" },
        { value: "luminance", label: "Layer Luminance" },
        { value: "horizontal-gradient", label: "Horizontal Gradient" },
      ], default: "image" },
      { type: "text", key: "mapSource", label: "Map Source (doc:layer)", default: "", placeholder: "layer:<docId>:<layerId> or doc:<docId>" },
      { type: "select", key: "tileMap", label: "Map Placement", options: [
        { value: "tile", label: "Tile" },
        { value: "stretch", label: "Stretch to Fit" },
      ], default: "tile" },
      { type: "select", key: "edgeMode", label: "Undefined Areas", options: [
        { value: "repeat", label: "Repeat Edge Pixels" },
        { value: "wrap", label: "Wrap Around" },
        { value: "transparent", label: "Set to Transparent" },
      ], default: "repeat" },
    ],
    apply: (src, p, ctx) => displace(
      src,
      Number(p.scaleX ?? (String(p.mode) === "vertical" ? 0 : p.scale ?? 24)),
      Number(p.scaleY ?? (String(p.mode) === "horizontal" ? 0 : p.scale ?? 24)),
      String(p.map ?? "image"),
      String(p.edgeMode ?? "repeat"),
      ctx?.displacementMap ?? null,
      String(p.tileMap ?? "tile") === "tile",
    ),
  },
  "diffuse-glow": {
    id: "diffuse-glow",
    name: "Diffuse Glow",
    category: "Distort",
    params: [
      { type: "slider", key: "grain", label: "Graininess", min: 0, max: 100, step: 1, default: 35 },
      { type: "slider", key: "glow", label: "Glow Amount", min: 0, max: 100, step: 1, default: 45 },
      { type: "slider", key: "clear", label: "Clear Amount", min: 0, max: 100, step: 1, default: 35 },
    ],
    apply: (src, p) => diffuseGlow(src, Number(p.grain), Number(p.glow), Number(p.clear)),
  },
  "ocean-ripple": {
    id: "ocean-ripple",
    name: "Ocean Ripple",
    category: "Distort",
    params: [
      { type: "slider", key: "size", label: "Ripple Size", min: 4, max: 80, step: 1, default: 18 },
      { type: "slider", key: "magnitude", label: "Magnitude", min: 0, max: 50, step: 1, default: 12 },
    ],
    apply: (src, p) => oceanRipple(src, Number(p.size), Number(p.magnitude)),
  },
  fragment: {
    id: "fragment",
    name: "Fragment",
    category: "Pixelate",
    params: [],
    apply: (src) => fragment(src),
  },
  facet: {
    id: "facet",
    name: "Facet",
    category: "Pixelate",
    params: [
      { type: "slider", key: "threshold", label: "Threshold", min: 4, max: 80, step: 1, default: 22 },
    ],
    apply: (src, p) => facet(src, Number(p.threshold ?? 22)),
  },
  pointillize: {
    id: "pointillize",
    name: "Pointillize",
    category: "Pixelate",
    params: [
      { type: "slider", key: "cellSize", label: "Cell Size", min: 3, max: 96, step: 1, default: 8, suffix: "px" },
      { type: "select", key: "background", label: "Background", options: [
        { value: "#ffffff", label: "White" },
        { value: "#000000", label: "Black" },
        { value: "#7f7f7f", label: "Gray" },
      ], default: "#ffffff" },
    ],
    apply: (src, p) => pointillize(src, Number(p.cellSize ?? 8), String(p.background ?? "#ffffff")),
  },
  shear: {
    id: "shear",
    name: "Shear",
    category: "Distort",
    params: [
      { type: "slider", key: "amount", label: "Amount", min: -100, max: 100, step: 1, default: 30 },
      { type: "select", key: "edgeMode", label: "Undefined Areas", options: [
        { value: "repeat", label: "Repeat Edge Pixels" },
        { value: "wrap", label: "Wrap Around" },
        { value: "transparent", label: "Set to Transparent" },
      ], default: "repeat" },
    ],
    apply: (src, p) => shear(src, Number(p.amount ?? 30), String(p.edgeMode ?? "repeat")),
  },
  tiles: {
    id: "tiles",
    name: "Tiles",
    category: "Stylize",
    params: [
      { type: "slider", key: "tiles", label: "Number of Tiles", min: 2, max: 99, step: 1, default: 10 },
      { type: "slider", key: "maxOffset", label: "Maximum Offset", min: 1, max: 99, step: 1, default: 10, suffix: "%" },
      { type: "select", key: "fill", label: "Fill Empty Area With", options: [
        { value: "background", label: "Background" },
        { value: "foreground", label: "Foreground" },
        { value: "transparent", label: "Transparent" },
      ], default: "background" },
    ],
    apply: (src, p) => tilesFilter(src, Number(p.tiles ?? 10), Number(p.maxOffset ?? 10), String(p.fill ?? "background")),
  },
  diffuse: {
    id: "diffuse",
    name: "Diffuse",
    category: "Stylize",
    params: [
      { type: "select", key: "mode", label: "Mode", options: [
        { value: "normal", label: "Normal" },
        { value: "darken", label: "Darken Only" },
        { value: "lighten", label: "Lighten Only" },
        { value: "anisotropic", label: "Anisotropic" },
      ], default: "normal" },
      { type: "slider", key: "amount", label: "Strength", min: 1, max: 100, step: 1, default: 30 },
    ],
    apply: (src, p) => diffuse(src, String(p.mode ?? "normal"), Number(p.amount ?? 30)),
  },
}
