import type {
  CapabilityKind,
  CapabilityRecord,
  CapabilityStatus,
} from "./capability-types"

export type {
  CapabilityDocumentSnapshot,
  CapabilityKind,
  CapabilityRecord,
  CapabilityStatus,
  CapabilityWarning,
} from "./capability-types"

export const CAPABILITY_STATUS_ORDER: CapabilityStatus[] = [
  "complete",
  "usable",
  "approximation",
  "stub",
  "unsupported",
]

const records = [
  {
    id: "tool.quick-selection",
    label: "Quick Selection Tool",
    kind: "tool",
    status: "usable",
    summary: "Local edge-aware region growing selection from a seed point.",
    limitations: ["No proprietary cloud/Sensei model is bundled.", "Selection quality depends on visible color, alpha, and edge evidence in local pixels."],
    recommendedAction: "Use for local edge-bounded selections; use Select and Mask for refinement.",
    testCoverage: "unit",
  },
  {
    id: "tool.object-aware-selection",
    label: "Offline Object-Aware Selection",
    kind: "tool",
    status: "usable",
    summary: "Select Subject, Select Sky, Select Background, and Object Selection use deterministic foreground/background models, connected sky/background extraction, component scoring, and local edge evidence.",
    limitations: ["Reports nativeAiParity=false because no proprietary ML segmentation model is bundled.", "Complex scenes can still require Select and Mask cleanup."],
    recommendedAction: "Use Sample All Layers for composited 8-bit selection previews or the active high-bit layer path when preserving subtle magnetic edge contrast matters.",
    testCoverage: "unit",
  },
  {
    id: "tool.selection-matting",
    label: "Selection Edge Matting",
    kind: "tool",
    status: "usable",
    summary: "Select and Mask refinements include local transparency matting, filament preservation for hair/fur-like edges, decontamination, and connectivity cleanup.",
    limitations: ["Offline color/alpha matting is deterministic and not a neural portrait matting model."],
    recommendedAction: "Use Refine Edge Brush or Select and Mask when the first-pass object-aware mask misses thin boundary detail.",
    testCoverage: "unit",
  },
  {
    id: "tool.magnetic-lasso",
    label: "Magnetic Lasso",
    kind: "tool",
    status: "usable",
    summary: "Traces hysteresis-linked, non-max-suppressed local edge paths with width, contrast, hysteresis, smoothing, and high-bit typed-array source support.",
    limitations: ["Still uses local edge energy, not semantic object understanding."],
    testCoverage: "unit",
  },
  {
    id: "tool.slice-select",
    label: "Slice Select Tool",
    kind: "tool",
    status: "usable",
    summary: "Selects and edits existing browser export slices.",
    limitations: ["No ImageReady-era slice optimization metadata.", "Slice export remains browser raster based."],
    testCoverage: "reachability",
  },
  {
    id: "tool.freeform-pen",
    label: "Freeform Pen Tool",
    kind: "tool",
    status: "usable",
    summary: "Creates editable path metadata from freehand pointer input, with Scharr/Canny-style magnetic thinning, hysteresis edge linking, and smoothing controls.",
    limitations: ["Magnetic fitting depends on browser-rendered pixel contrast rather than Photoshop's native image-analysis stack."],
    testCoverage: "unit",
  },
  {
    id: "tool.anchor-editing",
    label: "Anchor Point Editing Tools",
    kind: "tool",
    status: "usable",
    summary: "Adds/removes/converts anchors, drags anchors and Bezier handles directly on canvas, supports symmetric/broken handle modes, subpaths, shape computed paths, and SVG path export.",
    limitations: ["Photoshop-private path metadata is represented through the app path model when exported outside the project format."],
    testCoverage: "unit",
  },
  {
    id: "tool.vertical-type",
    label: "Vertical Type Tool",
    kind: "tool",
    status: "usable",
    summary: "Creates editable text layers with vertical glyph rendering metadata and uses embedded OpenType metrics when local font bytes are available.",
    limitations: ["Browser canvas antialiasing can still differ from Photoshop's private rasterizer."],
    testCoverage: "reachability",
  },
  {
    id: "typography.variable-fonts",
    label: "Variable Font Axes",
    kind: "typography",
    status: "usable",
    summary: "Text layers store variable axis metadata, parse embedded OpenType fvar ranges and named instances, and apply CSS canvas font-variation settings.",
    limitations: ["Without embedded font bytes, discovery falls back to browser/font availability."],
    testCoverage: "unit",
  },
  {
    id: "typography.font-diagnostics",
    label: "Font Preview and Missing-Font Diagnostics",
    kind: "typography",
    status: "usable",
    summary: "Font preview specs, browser availability checks, per-layer missing font reports, fallback substitutions, and embedded font export payloads are available.",
    limitations: ["Raster exports carry fonts in XMP metadata; image pixels remain flattened by the target raster format."],
    testCoverage: "unit",
  },
  {
    id: "typography.match-font",
    label: "Match Font",
    kind: "typography",
    status: "usable",
    summary: "Ranks local/browser font candidates from editable text geometry or raster image-recognition metrics.",
    limitations: ["Image recognition is browser-local and model-light; it does not call Adobe Sensei services."],
    testCoverage: "unit",
  },
  {
    id: "typography.text-editing",
    label: "Find/Replace Text Across Layers",
    kind: "typography",
    status: "usable",
    summary: "Searches editable text layers, applies case/word-aware replacement, and reports changed layers and match positions.",
    limitations: ["Raster-only text pixels cannot be edited as text."],
    testCoverage: "unit",
  },
  {
    id: "typography.shape-path-text",
    label: "Text Inside Shape and Text to Path",
    kind: "typography",
    status: "usable",
    summary: "Text layers can use shape area containers and can be converted to editable paths using exact embedded OpenType glyf outlines when font bytes are available.",
    limitations: ["Without embedded font bytes, conversion falls back to approximate browser-local glyph boxes."],
    testCoverage: "unit",
  },
  {
    id: "typography.opentype-aa",
    label: "OpenType Controls and Anti-Alias Modes",
    kind: "typography",
    status: "usable",
    summary: "Text rendering stores and applies ligature, alternates, figures, fraction, small-caps, and Photoshop-style anti-alias metadata.",
    limitations: ["Browser canvas support for some OpenType tags varies by engine and font."],
    testCoverage: "unit",
  },
  {
    id: "typography.3d-text",
    label: "3D Text Extrusion",
    kind: "typography",
    status: "approximation",
    summary: "Creates browser-native 3D scene layers with per-glyph extrusion geometry, material, lights, and rendered previews.",
    limitations: ["Glyph meshes are editable approximations, not exact font outline triangulations."],
    testCoverage: "unit",
  },
  {
    id: "3d.advanced-import-export",
    label: "Advanced 3D Import / Export",
    kind: "3d",
    status: "approximation",
    summary: "Imports browser-readable 3DS/KMZ/U3D subsets, exports binary 3DS, KMZ ZIP, and structured U3D browser-local payloads alongside OBJ/DAE, and preserves local animation metadata.",
    limitations: ["Exact proprietary vendor chunks, compressed binary package parity, and proprietary U3D blocks are approximated."],
    testCoverage: "unit",
  },
  {
    id: "3d.material-uv-paint",
    label: "UV, Material, and 3D Surface Painting",
    kind: "3d",
    status: "usable",
    summary: "Scene metadata supports planar UV assignment, material UV scale/offset, editable material parameters, and texture paint strokes baked into editable browser-local atlases.",
    limitations: ["External proprietary shader graphs and GPU-native texture stacks are approximated as editable atlas pixels and import metadata."],
    testCoverage: "unit",
  },
  {
    id: "3d.raytrace-cross-section-print",
    label: "Ray Trace, Cross Section, and 3D Print Checks",
    kind: "3d",
    status: "approximation",
    summary: "Sampled CPU ray-traced previews, cross-section cap metadata, animation evaluation, slicer-style print plans, and non-manifold/build-volume/thin-wall print checks run locally.",
    limitations: ["No GPU path tracer, vendor-grade physical renderer, or direct printer-driver integration."],
    testCoverage: "unit",
  },
  {
    id: "video.timeline-editing",
    label: "Video Trim, Split, Transitions, and Groups",
    kind: "video",
    status: "usable",
    summary: "Video layers support frame-snapped trim ranges, visual handle/tick models, split clip creation, cross-dissolve/fade/wipe transitions, thumbnail extraction, and video group records.",
    limitations: ["Unreadable source media fails with explicit timeout errors instead of hanging."],
    testCoverage: "unit",
  },
  {
    id: "video.audio-mixing",
    label: "Audio Mixing and Playback Model",
    kind: "video",
    status: "usable",
    summary: "Audio tracks store pan, fades, mute state, volume, active mix gains, OfflineAudioContext WAV export data, and mux-stream fade/pan automation for final audiovisual export.",
    limitations: [],
    testCoverage: "unit",
  },
  {
    id: "video.export-presets-frame-animation",
    label: "Video Export Presets and Frame Animation Conversion",
    kind: "video",
    status: "usable",
    summary: "Named export presets resolve to real MediaRecorder MP4/H.264 or WebM muxing when available, and unsupported codecs fall back to a deterministic ZIP frame/audio package.",
    limitations: [],
    testCoverage: "unit",
  },
  {
    id: "preferences.performance-settings",
    label: "RAM, Cache, Scratch Disk, and GPU Preferences",
    kind: "preferences",
    status: "usable",
    summary: "Preferences store Quality/Balanced/Performance modes plus RAM allocation, cache levels, tile size, history state limits, scratch storage quotas, WebGL/worker preferences, and browser fallback policy summaries.",
    limitations: ["Browser preferences cannot reserve operating-system RAM, select physical disks directly, or force native GPU driver behavior."],
    testCoverage: "unit",
  },
  {
    id: "preferences.file-handling-history",
    label: "File Handling Policies and History Log",
    kind: "preferences",
    status: "usable",
    summary: "File handling policies cover autosave intervals, close prompts, project-format preference, metadata preservation, compatibility warnings, missing-font handling, large-file handling, and bounded history logs.",
    limitations: ["History text-file output is exported by the browser on demand rather than continuously appended to an arbitrary local path."],
    testCoverage: "unit",
  },
  {
    id: "preferences.cursor-tool-units",
    label: "Cursor, Tool Behavior, Units, Rulers, and Grid Preferences",
    kind: "preferences",
    status: "usable",
    summary: "Tool cursor style, brush-preview crosshairs, tooltip behavior, brush smoothing, shift-cycling, auto-select behavior, ruler units, type units, print resolution, calibrated screen DPI, grid subdivision/color/opacity, pixel grid, snap, smart guides, and ruler origin are persisted and applied to active documents.",
    limitations: ["Some tool behavior settings remain local editor preferences rather than operating-system level cursor settings."],
    testCoverage: "unit",
  },
  {
    id: "preferences.import-export-reset",
    label: "Preference Set Import, Export, and Reset",
    kind: "preferences",
    status: "usable",
    summary: "Preference sets normalize old localStorage values, import/export versioned JSON, validate malformed imports with section-specific errors, support drag-and-drop JSON imports, and can import only selected preference sections.",
    limitations: ["Preference sync is local to the browser profile; no cloud account sync is provided."],
    testCoverage: "unit",
  },
  {
    id: "preferences.technology-previews",
    label: "Technology Preview Preferences",
    kind: "preferences",
    status: "usable",
    summary: "Technology Previews exposes experimental feature flags with per-toggle help and risk text, section reset behavior, and import/export coverage through preference sets.",
    limitations: ["Preview flags expose browser-local experimental paths only; they do not guarantee Adobe beta parity or hardware support."],
    testCoverage: "e2e",
  },
  {
    id: "tool.shape-rounded-rect",
    label: "Rounded Rectangle Tool",
    kind: "tool",
    status: "complete",
    summary: "Creates shape layers with live uniform and per-corner radius metadata, on-canvas corner handles, resize-aware radius scaling, cached path transforms, and PSD/project round-trip markers.",
    testCoverage: "unit",
  },
  {
    id: "tool.shape-polygon",
    label: "Polygon and Triangle Tools",
    kind: "tool",
    status: "usable",
    summary: "Creates polygon shape layers with side-count metadata.",
    limitations: ["Advanced star/path component options are limited to app presets."],
    testCoverage: "reachability",
  },
  {
    id: "format.psd",
    label: "PSD",
    kind: "format",
    status: "approximation",
    summary: "PSD import/export uses ag-psd with broad round-trip coverage: layer effects, adjustments, advanced blending, smart filters/objects, vector masks, shapes, text, paths, alpha/spot channels, guides, slices, comps, metadata, resolution, global light, and notes. App-only fields use marker-name encoding to survive vanilla ag-psd writes.",
    limitations: [
      "Pixel rendering and brush surfaces remain browser 8-bit RGBA even when bitDepth/colorMode metadata indicates 16/32-bit or CMYK.",
      "ag-psd's writer hardcodes RGB color mode and 8 bpc on disk; high-bit/CMYK/Lab data is preserved as side-band metadata and rasterized for display.",
      "Some adjustments (shadows-highlights, hdr-toning, desaturate, match-color, replace-color, equalize) round-trip through marker-name encoding.",
    ],
    recommendedAction: "Use the project format for maximum app metadata preservation when round-trip fidelity outside this app matters.",
    testCoverage: "e2e",
  },
  {
    id: "psd.color-modes",
    label: "PSD Color Modes and Bit Depth",
    kind: "format",
    status: "approximation",
    summary: "PSD color mode (Bitmap/Grayscale/Indexed/RGB/CMYK/Lab/Multichannel/Duotone) and bit depth (1/8/16/32) are detected on import; ICC profile bytes are preserved through the document and re-attached on export.",
    limitations: [
      "ag-psd's writer can only encode RGB at 8 bpc; non-RGB modes are stored as document metadata and exports remain RGB on disk.",
      "ICC transforms cover the supported browser-local profile set; arbitrary vendor profiles and production separations still need a certified CMM.",
    ],
    dependsOn: ["color.high-bit-pipeline", "color.icc-conversion"],
    testCoverage: "unit",
  },
  {
    id: "psd.effects-adjustments",
    label: "PSD Layer Effects and Adjustment Layers",
    kind: "format",
    status: "approximation",
    summary: "Layer effects (drop/inner shadow, outer/inner glow, bevel, satin, color/gradient/pattern overlay, stroke) and 22 adjustment layer types round-trip; 16 use native ag-psd descriptors and 6 use marker-name encoding.",
    limitations: [
      "Adjustment descriptors lacking native ag-psd support are recovered via marker layers; opening in older Photoshop builds may show generic adjustment labels.",
      "Layer style global-light tracking follows the document's globalLight resource.",
    ],
    testCoverage: "unit",
  },
  {
    id: "psd.vector-text",
    label: "PSD Vector, Shapes, Text, and Paths",
    kind: "format",
    status: "approximation",
    summary: "Text layers (font/size/styles/color), shape layers (rect/ellipse/polygon/custom), per-layer vector masks, and document-level paths round-trip. Custom shape and extended text properties use marker-name encoding.",
    limitations: [
      "Embedded OpenType metrics and outlines are preserved locally; Photoshop private text raster hinting is not reproduced.",
      "ag-psd's 0x07D0+ path image resources are surfaced via a marker token attached to the PSD's top-level name.",
    ],
    testCoverage: "unit",
  },
  {
    id: "psd.channels-masks",
    label: "PSD Channels and Masks",
    kind: "format",
    status: "approximation",
    summary: "Raster layer masks (defaultColor/disabled/position), vector layer masks, saved alpha channels with pixel data, spot channels (via naming), and clipping-mask groups all round-trip.",
    limitations: [
      "Saved alpha channel pixels travel through a hidden marker group (__app_saved_channels__) because ag-psd does not surface saved-channel pixel records on its public Psd shape.",
      "Spot channels are encoded via the channel name '[spot:#rrggbb:opacity]name'.",
    ],
    testCoverage: "unit",
  },
  {
    id: "psd.resources-metadata",
    label: "PSD Image Resources and Metadata",
    kind: "format",
    status: "approximation",
    summary: "Guides, slices, layer comps, smart objects, document metadata (XMP), print settings, resolution/DPI, global light, and annotations round-trip through native ag-psd structures with marker-encoded payloads for full-fidelity recovery.",
    limitations: [
      "IPTC and EXIF blobs are not surfaced by ag-psd's public ImageResources, only XMP; IPTC/EXIF bytes are built internally for sidecar use.",
      "Smart object embedded bytes are capped at 30 MB.",
      "Print settings have lossy paper-size mapping; bleed and orientation use embedded extras.",
    ],
    testCoverage: "unit",
  },
  {
    id: "format.psb",
    label: "PSB",
    kind: "format",
    status: "usable",
    summary: "PSB import/export uses ag-psd Large Document mode for layered documents that fit browser canvas, file, and memory limits.",
    limitations: [
      "Photoshop-scale PSBs can still exceed browser memory/canvas limits; tile-only edit/export paths avoid full-document canvases, while native layered PSB encoding still depends on ag-psd/browser memory limits.",
      "Rendered editing remains browser 8-bit RGBA even when PSB metadata indicates higher bit depth or non-RGB color intent.",
    ],
    recommendedAction: "Use tile-only editing or tile-sequence export for oversized documents; use Save As PSB when the layered source fits local browser limits.",
    testCoverage: "unit",
  },
  {
    id: "format.raw-dng",
    label: "RAW/DNG",
    kind: "format",
    status: "approximation",
    summary: "Uses LibRaw WASM for browser-side RAW/DNG demosaic where available, falls back to embedded JPEG previews, and exports DNG-style TIFF/EP previews with Camera Raw sidecar recipes.",
    limitations: ["Proprietary camera/lens profile databases remain approximated locally, and raw sensor mosaics are not reconstructed from edited canvas pixels."],
    recommendedAction: "Use DNG export with the generated sidecar for browser-local RAW round trips; keep originals for production raw processing.",
    testCoverage: "reachability",
  },
  {
    id: "format.openexr",
    label: "OpenEXR",
    kind: "format",
    status: "approximation",
    summary: "OpenEXR import uses parse-exr to decode supported pixel channels into tone-mapped editable previews and exports scanline EXR plus arbitrary-channel, tiled/deep metadata, and multipart manifest workflows.",
    limitations: ["Production OCIO transforms and true HDR display are approximated by browser-local metadata and tone-mapped previews."],
    recommendedAction: "Use EXR import/export for local flattened interchange; verify scene-linear production files in dedicated EXR tooling.",
    testCoverage: "unit",
  },
  {
    id: "format.baseline-tiff",
    label: "Baseline TIFF",
    kind: "format",
    status: "usable",
    summary: "Decodes TIFF through UTIF2 with a local baseline fallback and exports flattened RGBA TIFF/BigTIFF data with metadata, custom fields, subdirectories, and high-bit samples.",
    limitations: ["Certified ICC conversion and production prepress CMYK separation fidelity remain outside the browser pipeline."],
    recommendedAction: "Use for local preview/import of simple TIFF assets; keep production TIFF handoff in dedicated prepress tools.",
    testCoverage: "unit",
  },
  {
    id: "format.pdf",
    label: "PDF",
    kind: "format",
    status: "approximation",
    summary: "PDF import renders pages to flattened editable raster layers through PDF.js, and export writes single-page or multi-page PDFs with app-readable text/vector, transparency-group, and annotation manifests.",
    limitations: ["External PDF editors may ignore the browser-local edit manifest; prepress-grade PDF/X authoring remains outside the browser pipeline."],
    recommendedAction: "Use PDF import/export for flattened page handoff plus browser-local edit recovery; keep production PDF/X work in dedicated layout tools.",
    testCoverage: "unit",
  },
  {
    id: "format.eps",
    label: "EPS / PostScript",
    kind: "format",
    status: "approximation",
    summary: "EPS import renders a broader safe subset including transforms, dashes, text, fill rules, paths, curves, colors, strokes, fills, and rectangles, and reconstructs editable records for supported operators.",
    limitations: ["No arbitrary PostScript execution, font resolution, separations, overprint handling, or unrestricted graphics-state evaluation."],
    recommendedAction: "Use EPS for safe-subset vector recovery and flattened handoff; use SVG/project format for richer editable local vector content.",
    testCoverage: "unit",
  },
  {
    id: "format.heif",
    label: "HEIF / HEIC",
    kind: "format",
    status: "approximation",
    summary: "HEIF/HEIC import uses the bundled decoder for primary-image RGBA previews, AVIF-backed HEIF export uses the browser encoder, and HEVC-backed HEIC containers are authored when a HEVC encoder callback is configured.",
    limitations: ["Auxiliary/depth image handling, live-photo pairing, and certified ICC conversion remain outside the browser pipeline."],
    recommendedAction: "Use configured HEVC callbacks for HEIC export, AVIF-backed HEIF where browser support is enough, and dedicated tooling for production conformance checks.",
    testCoverage: "unit",
  },
  {
    id: "format.jpeg2000",
    label: "JPEG 2000",
    kind: "format",
    status: "approximation",
    summary: "JPEG 2000 import decodes supported JP2/J2K codestreams into editable RGBA previews, and export writes codestream, JP2, JPX, and JPM containers with alpha, color boxes, ICC/profile metadata, and layer labels.",
    limitations: ["Production archival conformance validation remains a dedicated JPEG 2000 tooling step."],
    recommendedAction: "Use JPEG 2000 import/export for flattened interchange and verify profile-sensitive delivery files in dedicated JPEG 2000 tooling.",
    testCoverage: "unit",
  },
  {
    id: "format.tga-pnm",
    label: "TGA and Portable AnyMap",
    kind: "format",
    status: "usable",
    summary: "Decodes TGA true-color/grayscale/indexed RLE data plus PBM/PGM/PPM/PNM ASCII and binary rasters; exports TGA RLE and PBM/PGM/PPM from canvas pixels with native metadata records where available.",
    limitations: ["Imports resolve to browser 8-bit RGBA layers; vendor-private TGA developer tags outside the app record remain metadata-only."],
    testCoverage: "unit",
  },
  {
    id: "format.radiance-hdr",
    label: "Radiance HDR",
    kind: "format",
    status: "usable",
    summary: "Imports flat and RLE Radiance RGBE files into tone-mapped editable previews and exports flattened RGBE HDR files.",
    limitations: ["Canvas editing remains 8-bit RGBA; no scene-linear high dynamic range working space is provided."],
    testCoverage: "unit",
  },
  {
    id: "format.dicom",
    label: "DICOM",
    kind: "format",
    status: "approximation",
    summary: "Imports uncompressed MONOCHROME/RGB DICOM pixels through dicom-parser, inspects compressed transfer syntax metadata, and exports Secondary Capture DICOM with overlays, richer metadata, and non-clinical labels.",
    limitations: ["Clinical diagnostic validation and private hospital workflows remain outside this browser editor."],
    testCoverage: "unit",
  },
  {
    id: "export.browser-raster",
    label: "Browser Raster Export",
    kind: "export",
    status: "usable",
    summary: "Exports browser canvas encodings plus app-authored TIFF/BigTIFF/DNG, TGA, PNM, interlaced PNG, progressive JPEG, JPEG 2000, HEIF/HEIC, EXR, DICOM, PNG/JPEG metadata, ICC conversion, and profile chunks.",
    limitations: ["Production conformance for medical, prepress, and archival delivery still requires dedicated validators."],
    recommendedAction: "Use exported report/preflight notes for handoff limitations.",
    testCoverage: "e2e",
  },
  {
    id: "export.image-assets-generator",
    label: "Image Assets Generator",
    kind: "export",
    status: "usable",
    summary: "Parses Photoshop Generator-style layer names such as icon.png and 200% icon@2x.png, exports per-layer PNG/JPEG/WebP/GIF/AVIF assets, reports invalid names and filename conflicts, and can auto-run on save or change.",
    limitations: ["Change-based auto-export writes only after a folder has been connected with the browser File System Access API; otherwise save/manual generation downloads a ZIP archive."],
    recommendedAction: "Use the Assets panel Generator controls to connect an output folder for continuous writes.",
    testCoverage: "unit",
  },
  {
    id: "color.browser-rgba",
    label: "Browser 8-bit RGBA Pixel Pipeline",
    kind: "color",
    status: "usable",
    summary: "Canvas display, fallback operations, and browser-native preview surfaces use 8-bit RGBA ImageData.",
    limitations: ["The visible canvas preview is 8-bit RGBA; high-bit documents keep separate typed-array sources for supported edit and export paths."],
    recommendedAction: "Use the high-bit pipeline warnings to identify any operation that falls back to canvas preview data.",
    testCoverage: "unit",
  },
  {
    id: "color.icc-conversion",
    label: "ICC-Accurate Conversion",
    kind: "color",
    status: "usable",
    summary: "A browser-local ICC transform engine converts supported RGB, grayscale, and CMYK proof profiles plus embedded RGB matrix/TRC ICC profile bytes for assignment, conversion, soft proofing, gamut warnings, and raster export.",
    limitations: ["Arbitrary vendor ICC CLUT/device-link profiles and certified external CMM behavior remain outside the browser-local engine."],
    recommendedAction: "Use professional color-managed software for contract proofs that require certified press profiles.",
    testCoverage: "unit",
  },
  {
    id: "color.high-bit-pipeline",
    label: "16/32-bit Editing Pipeline",
    kind: "color",
    status: "usable",
    summary: "Typed-array high-bit sources are routed through high-bit-aware filters, adjustment-layer compositing, dedicated high-bit editing surfaces, brush/paint sync, pixel readout comparisons, separation analysis, half-float GPU planning, OCIO-style view transforms, and TIFF/PNM precision exports.",
    limitations: ["Final browser display remains a tone-mapped preview.", "Filters without typed implementations can still fall back through preview pixels."],
    recommendedAction: "Prefer TIFF or 16-bit PNM export when preserving high-bit sample precision matters.",
    testCoverage: "unit",
  },
  {
    id: "smart-object.linked",
    label: "Linked Smart Objects",
    kind: "smart-object",
    status: "usable",
    summary: "Smart object sources track embedded/linked metadata, permission-aware relink and update checks, polling notifications, missing/modified/current states, edit-contents save-back, replace/export contents, tile materialization, convert-to-layers, and local stack modes.",
    limitations: ["Browser File System Access handles cannot be serialized into project files; reopened projects preserve handle metadata and ask the user to relink when a live handle is unavailable.", "The browser cannot subscribe to native OS file-watcher events, so linked-source changes are detected by in-app polling while the editor is open."],
    recommendedAction: "Use project format for preserving local smart object source metadata.",
    testCoverage: "unit",
  },
  {
    id: "smart-object.filters",
    label: "Smart Filters",
    kind: "smart-object",
    status: "usable",
    summary: "Smart filter metadata, order, masks, opacity, blend mode, enable state, native placed-filter descriptors, filter-effect mask records, Blur Gallery mesh resources, and project/PSD metadata round trips are editable locally.",
    limitations: ["Photoshop-private smart filter resources beyond the implemented descriptors are preserved as app metadata or rasterized previews."],
    testCoverage: "e2e",
  },
  {
    id: "filter.blur-gallery",
    label: "Blur Gallery",
    kind: "filter",
    status: "usable",
    summary: "Field Blur, Iris Blur, Tilt-Shift, Path Blur, and Spin Blur have named local algorithms, spatially varying previews, on-canvas control state, and deterministic Photoshop-style mesh-resource serialization.",
    limitations: ["Uses the browser worker/tile pipeline rather than Adobe's private Blur Gallery GPU engine."],
    testCoverage: "unit",
  },
  {
    id: "workflow.camera-raw",
    label: "Camera Raw Filter",
    kind: "workflow",
    status: "usable",
    summary: "Camera Raw supports rendered-pixel edits plus RAW-style high-bit non-destructive recipes, XMP sidecars, camera profiles, lens-profile matching, masks, presets, snapshots, and batch application.",
    limitations: ["RAW demosaic depends on the browser RAW decoder path; Adobe's proprietary camera/lens profile database is approximated locally."],
    recommendedAction: "Keep the original RAW/DNG with the generated sidecar when production RAW round-trip fidelity matters.",
    testCoverage: "unit",
  },
  {
    id: "workflow.photomerge",
    label: "Photomerge",
    kind: "workflow",
    status: "usable",
    summary: "Local panorama merge uses contrast features, descriptor matching, translation/similarity/affine/homography solving, cylindrical/spherical projection, camera/lens correction, expanded canvas bounds, exposure compensation, and multiband-style overlap blending.",
    limitations: ["Camera/lens model quality depends on supplied metadata and browser-decoded pixels rather than Adobe's native Photomerge stack."],
    recommendedAction: "Use local alignment controls and projection options for browser-side stack workflows.",
    testCoverage: "unit",
  },
  {
    id: "workflow.hdr-merge",
    label: "HDR Merge",
    kind: "workflow",
    status: "usable",
    summary: "HDR merge aligns rendered or RAW-style high-bit exposure brackets, estimates scene-linear radiance, emits 32-bit float high-bit sources with tone-mapped previews, and exposes deghost masks, reference-frame selection, and exposure weighting controls.",
    limitations: ["The visible canvas preview remains 8-bit; production HDR display and Adobe HDR Pro UI parity are approximated."],
    testCoverage: "unit",
  },
  {
    id: "workflow.content-aware-scale",
    label: "Content-Aware Scale",
    kind: "workflow",
    status: "approximation",
    summary: "Uses local seam carving with gradient energy, protected-mask support in the core engine, and explicit fallback for large reductions.",
    limitations: ["Large changes can still fall back to resampling.", "No Photoshop protected skin-tone/object models."],
    testCoverage: "unit",
  },
  {
    id: "filter.worker-expanded",
    label: "Worker Filter Coverage",
    kind: "filter",
    status: "usable",
    summary: "Deterministic supported filters run off-main-thread when worker APIs are available.",
    limitations: ["Registry-heavy and complex filters use scheduled main-thread fallback."],
    testCoverage: "unit",
  },
  {
    id: "performance.large-documents",
    label: "Large Document Performance",
    kind: "performance",
    status: "usable",
    summary: "Canvas pooling, history patches, pixel batch reads, worker filters, tiled filter execution, tile-local compositor passes, performance mode controls, and a tiled backing store with OPFS spill reduce large-image stalls.",
    limitations: ["Full-document preview and legacy browser encoder paths can still hit canvas-area limits; dirty redraws and tile-sequence export use bounded tile surfaces."],
    testCoverage: "unit",
  },
  {
    id: "performance.opfs-scratch",
    label: "OPFS Scratch Storage",
    kind: "performance",
    status: "usable",
    summary: "Origin Private File System scratch directory holds tile spill-over and incremental autosave deltas; in-memory fallback when OPFS is unavailable.",
    limitations: ["Quota varies across browsers; the planner reserves headroom to avoid eviction at the OS layer."],
    testCoverage: "unit",
  },
  {
    id: "performance.tiled-backing-store",
    label: "Tiled Document Backing Store",
    kind: "performance",
    status: "usable",
    summary: "Document pixels are paged through fixed-size tiles with LRU eviction, OPFS spill, memory-budget tracking, tile-local operation planning, a user-facing operation dashboard, and smart object/3D/video layer tile rendering.",
    limitations: ["Unsupported plugin/private layer payloads still fall back to compatibility reports or flattened browser previews."],
    testCoverage: "unit",
  },
  {
    id: "performance.progressive-preview",
    label: "Progressive Preview Rendering",
    kind: "performance",
    status: "usable",
    summary: "Large documents and zoom transitions render a low-resolution draft first, then refine through cancellable stages to full quality.",
    limitations: ["Coarse stages use nearest-neighbor downsampling — the final pass replaces them within a few hundred milliseconds."],
    testCoverage: "unit",
  },
  {
    id: "performance.dirty-rect-invalidation",
    label: "Dirty-Rect Render Invalidation",
    kind: "performance",
    status: "usable",
    summary: "Render bus tracks dirty rectangles per layer and merges them across same-frame invalidations so the compositor can scissor its redraw.",
    limitations: ["Coverage above 60% promotes to a full-frame redraw to amortize bookkeeping cost."],
    testCoverage: "unit",
  },
  {
    id: "performance.memory-budget",
    label: "Memory Budget Enforcement",
    kind: "performance",
    status: "usable",
    summary: "A central tracker bounds history, tile cache, composite cache, and filter buffers; subscribers receive soft and hard pressure events.",
    limitations: ["Allocation sizes are declared by callers; the tracker does not introspect raw heap usage."],
    testCoverage: "unit",
  },
  {
    id: "performance.incremental-autosave",
    label: "Incremental Autosave",
    kind: "performance",
    status: "usable",
    summary: "Per-layer fingerprints drive a delta autosave chain backed by OPFS; full snapshots rebase the chain at a bounded interval.",
    limitations: ["Delta chain capped at ~8 entries and ~12 MB before a forced rebase."],
    testCoverage: "unit",
  },
  {
    id: "performance.offscreen-canvas",
    label: "OffscreenCanvas Adoption",
    kind: "performance",
    status: "usable",
    summary: "Capability detection picks OffscreenCanvas for intermediate composites, filter buffers, and worker transfers; falls back to HTMLCanvasElement when unsupported.",
    limitations: ["Some browsers expose OffscreenCanvas only on the main thread; worker transfer paths advertise their requirements explicitly."],
    testCoverage: "unit",
  },
  {
    id: "panel.browser-diagnostics",
    label: "Browser Diagnostics Panel",
    kind: "panel",
    status: "usable",
    summary: "Dedicated diagnostics panel reports health, scale confidence, tile-only operation status, canvas limits, WebGL renderer and extensions, OffscreenCanvas transfer support, MediaRecorder and image encoder support, OPFS quota, heap estimates, autosave status, and active fallback modes.",
    limitations: ["Runtime values depend on the current browser, GPU driver, privacy masking, and storage permission state."],
    recommendedAction: "Use the copy or export report actions when comparing browser capability differences across machines.",
    testCoverage: "e2e",
  },
  {
    id: "panel.accessibility-audit",
    label: "Editor Accessibility Metadata Audit Panel",
    kind: "panel",
    status: "usable",
    summary: "Accessibility audit mode checks keyboard shortcut conflicts, focus-trap declarations, compact touch targets, icon labels, and panel/tab metadata for keyboard discoverability.",
    limitations: ["Static panel metadata cannot prove every runtime focus transition; manual keyboard testing is still required for complex modal workflows."],
    recommendedAction: "Run the audit before shipping new panels, dialogs, or icon-only controls.",
    testCoverage: "unit",
  },
  {
    id: "external.generative-fill",
    label: "Generative Fill",
    kind: "external",
    status: "usable",
    summary: "Prompt-based fill/remove uses deterministic local inpainting by default and can route the same source/mask/prompt payload to a configured model-backed image-edit endpoint with generated-layer provenance.",
    limitations: ["Model quality, safety filtering, and licensing depend on the configured endpoint; local fallback is deterministic and not a neural model."],
    recommendedAction: "Set GENERATIVE_IMAGE_ENDPOINT and GENERATIVE_IMAGE_API_KEY for model-backed inpainting.",
    testCoverage: "unit",
  },
  {
    id: "external.native-plugins",
    label: "Adobe Plugin Runtime Compatibility",
    kind: "external",
    status: "approximation",
    summary: "Browser-safe UXP and CEP adapters expose sandboxed host APIs, CSInterface/evalScript shims, Action Manager descriptors, package import/export, and 8BF kernel execution.",
    limitations: [
      "Native 8BF binaries import as metadata unless paired with a safe kernel or browser-compatible adapter.",
      "The UXP/CEP adapters expose a documented browser subset, not Adobe's proprietary host process.",
    ],
    recommendedAction: "Use the browser plugin manifest for local automation; verify production Adobe plugins inside Photoshop.",
    testCoverage: "unit",
  },
  {
    id: "external.cloud-libraries",
    label: "Creative Cloud Libraries",
    kind: "external",
    status: "unsupported",
    summary: "Project-local asset records exist; Adobe cloud sync does not.",
    limitations: ["No Adobe account, licensing, or sync integration."],
    testCoverage: "reachability",
  },
] as const satisfies readonly CapabilityRecord[]

const CAPABILITY_BY_ID = new Map<string, CapabilityRecord>(records.map((record) => [record.id, record]))

const UNKNOWN_CAPABILITY: CapabilityRecord = {
  id: "unknown",
  label: "Unknown capability",
  kind: "external",
  status: "unsupported",
  summary: "No capability record is registered for this feature.",
  limitations: ["The feature cannot be classified until it is added to the registry."],
  recommendedAction: "Add a capability record before exposing this as supported.",
  testCoverage: "none",
}

export function listCapabilities(filter?: { kind?: CapabilityKind; status?: CapabilityStatus }) {
  return records.filter((record) => {
    if (filter?.kind && record.kind !== filter.kind) return false
    if (filter?.status && record.status !== filter.status) return false
    return true
  })
}

export function getCapability(id: string): CapabilityRecord {
  return CAPABILITY_BY_ID.get(id) ?? { ...UNKNOWN_CAPABILITY, id }
}

export function capabilityStatusRank(status: CapabilityStatus) {
  return CAPABILITY_STATUS_ORDER.indexOf(status)
}

export function isCapabilityUsable(id: string) {
  return ["complete", "usable", "approximation"].includes(getCapability(id).status)
}

export function summarizeCapabilities(items: readonly CapabilityRecord[]) {
  const summary: Record<CapabilityStatus, number> = {
    complete: 0,
    usable: 0,
    approximation: 0,
    stub: 0,
    unsupported: 0,
  }
  for (const item of items) summary[item.status] += 1
  return summary
}

export { capabilityWarningsForDocument } from "./capability-warnings"

export function capabilitiesForIds(ids: readonly string[]) {
  return ids.map(getCapability).sort((a, b) => capabilityStatusRank(a.status) - capabilityStatusRank(b.status))
}
