export type ToolId =
  | "move" | "marquee-rect" | "marquee-ellipse" | "marquee-row" | "marquee-col" | "lasso" | "lasso-polygon" | "lasso-magnetic" | "magic-wand" | "quick-selection" | "object-select" | "refine-edge-brush" | "crop" | "perspective-crop" | "slice" | "slice-select" | "frame" | "eyedropper" | "ruler" | "note" | "count" | "color-sampler" | "red-eye" | "spot-healing" | "healing-brush" | "patch-tool" | "content-aware-move" | "brush" | "pencil" | "mixer-brush" | "clone-stamp" | "history-brush" | "art-history-brush" | "eraser" | "gradient" | "paint-bucket" | "blur" | "sharpen" | "smudge" | "dodge" | "burn" | "sponge" | "pen" | "freeform-pen" | "curvature-pen" | "add-anchor-point" | "delete-anchor-point" | "convert-point" | "type" | "type-vertical" | "type-mask-horizontal" | "type-mask-vertical" | "path-select" | "direct-select" | "shape-rect" | "shape-rounded-rect" | "shape-ellipse" | "shape-polygon" | "shape-star" | "shape-triangle" | "shape-line" | "custom-shape" | "artboard" | "hand" | "rotate-view" | "zoom" | "transform" | "select-subject" | "remove-tool" | "select-sky" | "select-background" | "color-replace" | "pattern-stamp" | "magic-eraser" | "background-eraser" | "material-eyedropper" | "material-drop"

export interface SelectionOptions { mode: "new" | "add" | "subtract" | "intersect"; feather: number; antiAlias: boolean; tolerance: number; contiguous: boolean; sampleAllLayers?: boolean; sampleSize?: "point" | "3x3" | "5x5" | "11x11" | "31x31" | "51x51" | "101x101"; autoEnhance?: boolean; quickGrowAmount?: number; magneticWidth?: number; magneticContrast?: number; magneticHysteresis?: number; magneticSmoothing?: number; magneticFrequency?: number; magneticPenPressure?: boolean }
export interface TextOptions { font: string; size: number; weight: "normal" | "bold"; italic: boolean; align: "left" | "center" | "right" }
export interface ShapeOptions { fill: string; stroke: string; strokeWidth: number; radius: number }
export interface CropState { active: boolean; bounds: { x: number; y: number; w: number; h: number } | null }
export interface TransformState { active: boolean; layerId: string; source: HTMLCanvasElement | null; bounds: { x: number; y: number; w: number; h: number }; tx: number; ty: number; rotation: number; scaleX: number; scaleY: number; skewX: number; skewY: number; referencePoint?: "tl" | "tc" | "tr" | "ml" | "mc" | "mr" | "bl" | "bc" | "br"; constrainProportions?: boolean; interpolation?: "nearest" | "bilinear" | "bicubic" | "bicubic-smoother" | "bicubic-sharper"; perspective?: { tl: { x: number; y: number }; tr: { x: number; y: number }; br: { x: number; y: number }; bl: { x: number; y: number } } }

import type { BlendMode } from "./types/core"
export type { BlendMode } from "./types/core"
export type LayerKind = "raster" | "text" | "shape" | "group" | "smart-object" | "adjustment" | "frame" | "artboard" | "3d" | "video"
import type { TextProps, ShapeProps, PathHandleMode, PathProps, MultiGradient } from "./types/typography"
export * from "./types/typography"

export interface LayerStyle {
  stroke?: { enabled: boolean; color: string; size: number; position: "inside" | "outside" | "center"; opacity?: number; blendMode?: BlendMode; fillType?: "color" | "gradient"; gradient?: MultiGradient }
  outerGlow?: { enabled: boolean; color: string; size: number; opacity: number; blendMode?: BlendMode; spread?: number; range?: number; noise?: number; contour?: "linear" | "soft" | "sharp" | "ring" | "cone" }
  innerGlow?: { enabled: boolean; color: string; size: number; opacity: number; blendMode?: BlendMode; source?: "edge" | "center"; choke?: number; range?: number; noise?: number; contour?: "linear" | "soft" | "sharp" | "ring" | "cone" }
  innerShadow?: { enabled: boolean; color: string; size: number; offsetX: number; offsetY: number; opacity: number; blendMode?: BlendMode; angle?: number; distance?: number; choke?: number; useGlobalLight?: boolean }
  bevel?: { enabled: boolean; style: "inner" | "outer" | "emboss" | "pillow"; direction?: "up" | "down"; depth: number; size: number; soften: number; angle: number; altitude: number; highlight: string; shadow: string; opacity: number; highlightOpacity?: number; shadowOpacity?: number; highlightBlendMode?: BlendMode; shadowBlendMode?: BlendMode; useGlobalLight?: boolean; contour?: "linear" | "soft" | "sharp" | "ring" | "cone" }
  satin?: { enabled: boolean; color: string; angle: number; distance: number; size: number; opacity: number; blendMode?: BlendMode; invert?: boolean }
  colorOverlay?: { enabled: boolean; color: string; opacity: number; blendMode?: BlendMode }
  gradientOverlay?: { enabled: boolean; gradient: MultiGradient; opacity: number; blendMode?: BlendMode }
  patternOverlay?: { enabled: boolean; pattern: "checker" | "dots" | "lines" | "noise" | string; scale: number; opacity: number; color?: string; blendMode?: BlendMode; align?: boolean; phase?: { x: number; y: number } }
  dropShadow?: { enabled: boolean; color: string; size: number; offsetX: number; offsetY: number; opacity: number; blendMode?: BlendMode; angle?: number; distance?: number; spread?: number; noise?: number; useGlobalLight?: boolean; contour?: "linear" | "soft" | "sharp" | "ring" | "cone" }
}
export interface BlendIfRange { black: number; blackFeather: number; whiteFeather: number; white: number }
export type BlendIfChannel = "gray" | "r" | "g" | "b"
export type BlendIfChannels = Partial<Record<BlendIfChannel, BlendIfRange>>
export interface AdvancedBlending { fillOpacity: number; knockout: "none" | "shallow" | "deep"; channels: { r: boolean; g: boolean; b: boolean }; blendIfThis: BlendIfRange; blendIfUnderlying: BlendIfRange; blendIfThisChannels?: BlendIfChannels; blendIfUnderlyingChannels?: BlendIfChannels; blendIfActiveChannel?: BlendIfChannel; transparencyShapesLayer?: boolean; layerMaskHidesEffects?: boolean; vectorMaskHidesEffects?: boolean }
export interface BlurGalleryMeshResource { signature: "8BIM"; resourceKey: "blurGalleryMesh"; version: 1; descriptor: { filterId: string; params: Record<string, number | string | boolean>; controlState: { selectedFieldPinIndexes: number[]; selectedPathPointIndexes: number[]; activeControl: string | null; previewQuality: "full" | "interactive" }; mesh: unknown }; payloadBase64: string; checksum: string }
export interface SmartFilter { id: string; filterId: string; name: string; enabled: boolean; opacity?: number; blendMode?: BlendMode; params: Record<string, number | string | boolean>; mask?: HTMLCanvasElement | null; maskEnabled?: boolean; maskDensity?: number; maskFeather?: number; maskLinked?: boolean; blurGalleryMesh?: BlurGalleryMeshResource }
export interface SmartObjectEditPackage { id: string; name: string; version: number; createdAt: number; updatedAt: number; documentId?: string; layerCount?: number; sourceHash?: string }
export interface SmartObjectSource { width: number; height: number; canvas?: HTMLCanvasElement | null; id?: string; name?: string; linkType?: "embedded" | "linked"; fileName?: string; relativePath?: string; status?: "current" | "missing" | "modified" | "embedded"; embedded?: boolean; updatedAt?: number; fileHandle?: FileSystemFileHandle; fileHandleName?: string; handlePermission?: PermissionState | "unsupported"; lastKnownModified?: number; lastKnownSize?: number; sourceHash?: string; editPackage?: SmartObjectEditPackage; exportedAt?: number; relinkedAt?: number }
export type AdjustmentType = "brightness-contrast" | "levels" | "curves" | "exposure" | "vibrance" | "hue-saturation" | "color-balance" | "black-white" | "photo-filter" | "channel-mixer" | "color-lookup" | "invert" | "posterize" | "threshold" | "gradient-map" | "selective-color" | "shadows-highlights" | "hdr-toning" | "desaturate" | "match-color" | "replace-color" | "equalize"
export interface AdjustmentProps { type: AdjustmentType; params: Record<string, number | string | boolean> }
export interface FrameProps { shape: "rect" | "ellipse"; x: number; y: number; w: number; h: number; imageCanvas?: HTMLCanvasElement | null }
export interface ArtboardProps { x: number; y: number; w: number; h: number; background: string }

import type { ThreeDScene, VideoKeyframe, VideoTransition, AudioTrack, VideoLayerProps, VideoGroupProps, PluginDescriptor, VariableDataSet } from "./types/rendering"
export * from "./types/rendering"
export interface DocumentModeSettings { mode: "RGB" | "CMYK" | "Grayscale" | "Duotone" | "Indexed" | "Multichannel" | "Bitmap"; duotone?: unknown; indexed?: unknown; multichannel?: unknown; bitmap?: unknown; trap?: { enabled: boolean; widthPx: number; strength: number } }
export interface Layer { id: string; name: string; kind?: LayerKind; visible: boolean; locked: boolean; lockTransparency?: boolean; lockDraw?: boolean; lockMove?: boolean; lockAll?: boolean; smartObject?: boolean; opacity: number; fillOpacity?: number; advancedBlending?: AdvancedBlending; blendMode: BlendMode; linkGroupId?: string; canvas: HTMLCanvasElement; mask?: HTMLCanvasElement | null; maskEnabled?: boolean; vectorMask?: PathProps | null; clipped?: boolean; style?: LayerStyle; childIds?: string[]; parentId?: string; expanded?: boolean; text?: TextProps; shape?: ShapeProps; path?: PathProps; adjustment?: AdjustmentProps; frame?: FrameProps; artboard?: ArtboardProps; threeD?: ThreeDScene; video?: VideoLayerProps; videoGroup?: VideoGroupProps; colorLabel?: "none" | "red" | "orange" | "yellow" | "green" | "blue" | "violet" | "gray"; notes?: LayerNote[]; metadata?: LayerMetadata; smartFilters?: SmartFilter[]; smartSource?: SmartObjectSource }
export interface Selection { bounds: { x: number; y: number; w: number; h: number } | null; shape: "rect" | "ellipse" | "polygon" | "freehand" | "wand" | "color"; mask?: HTMLCanvasElement | null; feather?: number; diagnostics?: SelectionDiagnostics }
export type SelectionDiagnosticReason = "accepted" | "color" | "edge" | "alpha" | "limit" | "bounds"
export interface SelectionDiagnostics { acceptedPixels: number; rejectedPixels: number; coverageRatio: number; boundsTouchesCanvas: boolean; maxPixelsReached: boolean; queueExhausted: boolean; summary: string; reasonCounts: Record<SelectionDiagnosticReason, number>; reasonMap: Uint8ClampedArray }
export type QuickMaskPaintMode = "add" | "subtract" | "auto"
export interface AlphaChannel { id: string; name: string; canvas: HTMLCanvasElement; kind?: "alpha" | "spot"; spotColor?: string; spotOpacity?: number }
export interface Guide { id: string; orientation: "horizontal" | "vertical"; position: number; color?: string; name?: string; locked?: boolean; visible?: boolean }
export interface LayerNote { id: string; text: string; author?: string; color?: string; createdAt: number; updatedAt?: number }
export type ReviewStatus = "open" | "resolved"
export interface CommentReply { id: string; author: string; text: string; createdAt: number; updatedAt?: number }
export type AnnotationGeometry = { kind: "pin"; x: number; y: number } | { kind: "rect"; x: number; y: number; w: number; h: number } | { kind: "ellipse"; x: number; y: number; w: number; h: number } | { kind: "arrow"; x1: number; y1: number; x2: number; y2: number } | { kind: "freehand"; points: { x: number; y: number }[]; closed?: boolean }
export interface Note { id: string; x: number; y: number; author: string; text: string; color: string; kind?: "note" | "comment" | "annotation"; status?: ReviewStatus; replies?: CommentReply[]; tags?: string[]; geometry?: AnnotationGeometry; createdAt?: number; updatedAt?: number; resolvedAt?: number; resolvedBy?: string }
export interface Slice { id: string; x: number; y: number; w: number; h: number; name: string; url?: string; target?: string; altText?: string; format?: "png" | "jpeg" | "webp" | "gif" | "avif"; quality?: number; compression?: number; filename?: string; scale?: number; locked?: boolean; visible?: boolean }
export interface LayerMetadata { title?: string; description?: string; tags?: string[]; custom?: Record<string, string | number | boolean>; createdAt?: number; modifiedAt?: number }
export interface CountMarker { id: string; x: number; y: number; group: string; number: number }
export interface ColorSampler { id: string; x: number; y: number; label: string; rgba: [number, number, number, number] }
export interface LayerComp { id: string; name: string; state: Record<string, { visible: boolean; opacity: number; fillOpacity?: number; advancedBlending?: AdvancedBlending; blendMode: BlendMode; clipped?: boolean; maskEnabled?: boolean; vectorMask?: PathProps | null; style?: LayerStyle; text?: TextProps; shape?: ShapeProps; path?: PathProps; adjustment?: AdjustmentProps; smartFilters?: SmartFilter[]; colorLabel?: Layer["colorLabel"]; notes?: LayerNote[]; metadata?: LayerMetadata }>; activeLayerId?: string; selectedLayerIds?: string[]; createdAt?: number; updatedAt?: number }
export interface AssetLibraryItem { id: string; name: string; kind: "brush" | "gradient" | "pattern" | "style" | "swatch" | "shape" | "export" | "tool-preset" | "plugin" | "cloud-library" | "stock" | "font" | "icc-profile" | "variable-data" | "prepress"; group?: string; tags?: string[]; description?: string; payload: unknown; createdAt: number; updatedAt?: number }
export interface FrameLayerTransform { tx: number; ty: number; scaleX: number; scaleY: number; rotation: number }
export type FrameEasing = "hold" | "linear" | "ease-in" | "ease-out" | "ease-in-out"
export interface TimelineFrame { id: string; name: string; durationMs: number; layerVisibility: Record<string, boolean>; layerOpacity?: Record<string, number>; layerFillOpacity?: Record<string, number>; layerStyle?: Record<string, LayerStyle | null>; layerBlend?: Record<string, BlendMode>; layerTransform?: Record<string, FrameLayerTransform>; transition?: "hold" | "dissolve" | VideoTransition["kind"]; transitionDurationMs?: number; easing?: FrameEasing; audioLabel?: string; compId?: string; keyframes?: VideoKeyframe[]; audioTracks?: AudioTrack[]; thumbnail?: string }
export interface OnionSkinSettings { enabled: boolean; before: number; after: number; opacity: number; tint?: "none" | "red-cyan" | "red-blue" | "green-red" | "mono" }
export interface TimelineSettings { fps: number; loopCount: number; onionSkin?: OnionSkinSettings }
export interface DocumentReport { id: string; title: string; createdAt: number; source: "PSD Import" | "PSD Export" | "Project Import" | "Project Export" | "Batch Export" | "Image Assets Generator"; items: { label: string; status: "preserved" | "approximated" | "flattened" | "unsupported" | "info"; detail: string }[] }
export interface ImageAssetGeneratorSettings { enabled?: boolean; autoExportOnSave?: boolean; autoExportOnChange?: boolean; outputFolderName?: string; lastRunAt?: number; lastTrigger?: "manual" | "save" | "change"; lastSummary?: string }
export interface DocumentMetadata { title?: string; author?: string; description?: string; copyright?: string; keywords?: string[]; credit?: string; source?: string; createdAt?: string; modifiedAt?: string; contentCredentials?: ContentCredential[]; largeDocumentTileView?: LargeDocumentTileViewMetadata; largeDocumentInspection?: LargeDocumentInspectionMetadata; largeDocumentTileEdit?: LargeDocumentTileEditMetadata; psdRepairPlan?: PsdRepairPlanMetadata; psdNativeSource?: PsdNativeSourceSnapshotMetadata; imageAssetGenerator?: ImageAssetGeneratorSettings }
export interface PsdNativeSourceSnapshotMetadata { kind: "psd-native-source"; version: 1; sourceName: string; format: "psd" | "psb"; byteLength: number; width?: number; height?: number; colorMode?: string; bitDepth?: number; checksum: string; encoding: "base64"; data: string }
export interface PsdParsedStructureMetadata { layerCount?: number; colorMode?: string; bitDepth?: number; resources?: string[]; repairableItems?: string[] }
export interface PsdRepairPlanMetadata { summary: string; actions: { label: string; status: "represented" | "repairable" | "inspect-only"; localRepresentation: string; detail: string }[] }
export interface LargeDocumentTileViewMetadata { mode: "psb-tile-view"; sourceName: string; originalWidth: number; originalHeight: number; overviewScale: number; tileSize: number; tileColumns: number; tileRows: number; tileCount: number; selectedTile?: { col: number; row: number } }
export interface LargeDocumentInspectionMetadata { mode: "inspection"; sourceName: string; kind: "raster" | "psd" | "psb" | "project" | "advanced"; originalWidth: number; originalHeight: number; previewWidth: number; previewHeight: number; editable: false; reason: string; warnings: string[]; parsedStructure?: PsdParsedStructureMetadata }
export interface LargeDocumentTileEditMetadata { mode: "tile-edit"; parentDocId: string; sourceName: string; originalWidth: number; originalHeight: number; tileSize: number; tile: { col: number; row: number; x: number; y: number; width: number; height: number }; editable: true }
export interface ContentCredential { id: string; action: string; actor: string; software: string; createdAt: string; documentName: string; documentHash: string; layerCount: number; dimensions: { width: number; height: number }; ingredients: { id: string; name: string; kind?: LayerKind; visible: boolean; hash: string }[]; assertion: string }
export type ColorProfileName = "sRGB IEC61966-2.1" | "Display P3" | "Adobe RGB (1998)" | "ProPhoto RGB" | "Working CMYK" | "U.S. Web Coated SWOP v2" | "Japan Color 2001 Coated" | "Dot Gain 20%" | "Gray Gamma 2.2"
export interface ColorManagementSettings { assignedProfile: ColorProfileName; workingSpace: ColorProfileName; renderingIntent: "perceptual" | "relative-colorimetric" | "saturation" | "absolute-colorimetric"; blackPointCompensation: boolean; proofProfile: "None" | ColorProfileName; proofColors: boolean; gamutWarning: boolean; simulateBlackInk?: boolean; preserveNumbers?: boolean; proofChannels?: Array<"red" | "green" | "blue" | "cyan" | "magenta" | "yellow" | "black" | "gray">; proofPlateView?: "composite" | "ink" | "mask" }
export interface PrintSettings { paperSize: "Letter" | "A4" | "A3" | "Tabloid" | "Custom"; orientation: "portrait" | "landscape"; scale: number; bleedMm: number; cropMarks: boolean; registrationMarks: boolean; centerCropMarks?: boolean; colorBars?: boolean; description?: boolean; labels?: boolean; colorHandling: "app" | "printer"; proofPrint: boolean; printerProfile?: ColorManagementSettings["proofProfile"]; paperColor?: string; marksOffsetMm?: number; pagePosition?: "center" | "top-left" }
export interface PsDocument { id: string; name: string; width: number; height: number; zoom: number; layers: Layer[]; activeLayerId: string; selectedLayerIds: string[]; background: string; colorMode: DocumentModeSettings["mode"]; bitDepth: 8 | 16 | 32; selection: Selection; rotation?: 0 | 90 | 180 | 270; guides?: Guide[]; showGrid?: boolean; showSmartGuides?: boolean; gridSize?: number; snap?: boolean; snapToGrid?: boolean; snapToGuides?: boolean; quickMask?: boolean; quickMaskCanvas?: HTMLCanvasElement | null; quickMaskPaintMode?: QuickMaskPaintMode; notes?: Note[]; slices?: Slice[]; selectedSliceId?: string; counts?: CountMarker[]; countGroup?: string; colorSamplers?: ColorSampler[]; comps?: LayerComp[]; measurement?: { x1: number; y1: number; x2: number; y2: number } | null; channels?: AlphaChannel[]; rulerUnits?: "px" | "in" | "cm" | "mm" | "pt" | "pc"; rulerOrigin?: { x: number; y: number }; gridColor?: string; gridSubdivisions?: number; gridOpacity?: number; showPixelGrid?: boolean; globalLight?: { angle: number; altitude: number }; patternLibrary?: { id: string; name: string; type: "checker" | "dots" | "lines" | "noise"; color: string; scale: number }[]; stylePresets?: { id: string; name: string; style: LayerStyle }[]; gradientPresets?: { id: string; name: string; gradient: MultiGradient }[]; characterStyles?: Record<string, Partial<TextProps>>; paragraphStyles?: Record<string, Record<string, number | string | boolean>>; assetLibrary?: AssetLibraryItem[]; timelineFrames?: TimelineFrame[]; timelineSettings?: TimelineSettings; plugins?: PluginDescriptor[]; pluginStorage?: Record<string, Record<string, unknown>>; variableDataSets?: VariableDataSet[]; modeSettings?: DocumentModeSettings; reports?: DocumentReport[]; metadata?: DocumentMetadata; colorManagement?: ColorManagementSettings; printSettings?: PrintSettings; smartObjectParent?: { docId: string; layerId: string }; dpi?: number }
export interface CanvasPatch { x: number; y: number; w: number; h: number; canvas: HTMLCanvasElement }
export interface LayerSnapshot { id: string; name: string; kind?: LayerKind; visible: boolean; locked: boolean; lockTransparency?: boolean; lockDraw?: boolean; lockMove?: boolean; lockAll?: boolean; smartObject?: boolean; opacity: number; fillOpacity?: number; advancedBlending?: AdvancedBlending; blendMode: BlendMode; linkGroupId?: string; canvas: HTMLCanvasElement | null; canvasPatches?: CanvasPatch[]; mask?: HTMLCanvasElement | null; maskEnabled?: boolean; vectorMask?: PathProps | null; clipped?: boolean; style?: LayerStyle; childIds?: string[]; parentId?: string; expanded?: boolean; text?: TextProps; shape?: ShapeProps; path?: PathProps; adjustment?: AdjustmentProps; frame?: FrameProps; artboard?: ArtboardProps; threeD?: ThreeDScene; video?: VideoLayerProps; colorLabel?: Layer["colorLabel"]; smartFilters?: SmartFilter[]; smartSource?: Layer["smartSource"]; notes?: LayerNote[]; metadata?: LayerMetadata }
export interface HistoryEntry { id: string; label: string; layers: LayerSnapshot[]; activeLayerId: string; selectedLayerIds: string[]; thumb?: string; width?: number; height?: number; selection?: Selection; guides?: Guide[]; notes?: Note[]; slices?: Slice[]; counts?: CountMarker[]; colorSamplers?: ColorSampler[]; comps?: LayerComp[]; channels?: AlphaChannel[]; quickMask?: boolean; quickMaskCanvas?: HTMLCanvasElement | null; quickMaskPaintMode?: QuickMaskPaintMode; colorMode?: PsDocument["colorMode"]; modeSettings?: DocumentModeSettings; variableDataSets?: VariableDataSet[]; assetLibrary?: AssetLibraryItem[] }
export interface HistorySnapshot { id: string; name: string; createdAt: number; entry: HistoryEntry }
export interface MacroStep { id: string; label: string; createdAt: number; entry: HistoryEntry }
export interface MacroAction { id: string; name: string; folder?: string; createdAt: number; updatedAt: number; steps: MacroStep[] }
export * from "./types/tools"

declare global {
  interface HTMLCanvasElement { __compressedBlobId?: string; __origW?: number; __origH?: number; __moveSnapshot?: HTMLCanvasElement }
  interface Window { __psCustomShape?: string; __psCustomShapePreset?: ShapeProps; __psShapeOptions?: Partial<{ strokeWidth: number; radius: number; sides: number; innerRadiusRatio: number; vertexRoundness: number; polygonStarMode: boolean; smoothCorners: boolean; smoothIndent: boolean; rotation: number; cornerRadiusTL: number; cornerRadiusTR: number; cornerRadiusBR: number; cornerRadiusBL: number }>; __psPathOptions?: Partial<{ handleMode: PathHandleMode }> }
  interface CanvasRenderingContext2D { fontKerning?: string; fontFeatureSettings?: string; fontVariantLigatures?: string; fontVariantCaps?: string; fontVariationSettings?: string; letterSpacing?: string; textRendering?: string }
}
export {}
